# Generated by Django 6.0.2 on 2026-02-06 23:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("content_encrypted", models.BinaryField()),
                ("nonce", models.BinaryField()),
                ("version", models.IntegerField(default=1)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "documents",
                "indexes": [
                    models.Index(
                        fields=["last_accessed"], name="documents_last_ac_0fb76c_idx"
                    )
                ],
            },
        ),
    ]
