# Generated by Django 6.0.2 on 2026-02-07 15:23

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='read_key_hash',
            field=models.BinaryField(null=True),
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content_encrypted', models.BinaryField()),
                ('nonce', models.BinaryField()),
                ('read_key_hash', models.BinaryField(null=True)),
                ('version', models.IntegerField(default=1)),
                ('last_accessed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workspaces',
                'indexes': [models.Index(fields=['last_accessed'], name='workspaces_last_ac_951ee5_idx')],
            },
        ),
    ]
